import { describe, expect, it } from 'vitest'
import {
  calculateReportMetrics,
  type ReportItemRow,
  type ReportOrderRow,
} from './admin-reports'

describe('admin report metrics', () => {
  it('separates accepted value, cash collected, and COD balances across Cairo calendar days', () => {
    const orders: ReportOrderRow[] = [
      {
        id: 'order-1',
        status: 'payment_confirmed',
        subtotalAmount: 10_000,
        totalAmount: 9_700,
        shippingFeeAmount: 1_000,
        promoCode: 'WELCOME',
        promoDiscountAmount: 1_000,
        paymentPlan: 'full_upfront',
        paymentStatus: 'paid',
        instapayDiscountAmount: 300,
        amountDueNow: 9_700,
        amountPaid: 9_700,
        amountDueOnDelivery: 0,
        governorateName: 'Cairo',
        createdAt: new Date('2026-07-18T12:00:00.000Z'),
      },
      {
        id: 'order-2',
        status: 'payment_submitted',
        subtotalAmount: 7_500,
        totalAmount: 8_000,
        shippingFeeAmount: 1_000,
        promoCode: 'WELCOME',
        promoDiscountAmount: 500,
        paymentPlan: 'full_upfront',
        paymentStatus: 'payment_submitted',
        instapayDiscountAmount: 0,
        amountDueNow: 8_000,
        amountPaid: 0,
        amountDueOnDelivery: 0,
        governorateName: 'Cairo',
        createdAt: new Date('2026-07-18T14:00:00.000Z'),
      },
      {
        id: 'order-3',
        status: 'cancelled',
        subtotalAmount: 6_000,
        totalAmount: 6_000,
        shippingFeeAmount: 0,
        promoCode: null,
        promoDiscountAmount: 0,
        paymentPlan: 'full_upfront',
        paymentStatus: 'payment_rejected',
        instapayDiscountAmount: 0,
        amountDueNow: 6_000,
        amountPaid: 0,
        amountDueOnDelivery: 0,
        governorateName: 'Giza',
        createdAt: new Date('2026-07-19T10:00:00.000Z'),
      },
      {
        id: 'order-4',
        status: 'in_production',
        subtotalAmount: 12_000,
        totalAmount: 12_000,
        shippingFeeAmount: 1_000,
        promoCode: 'WELCOME',
        promoDiscountAmount: 1_000,
        paymentPlan: 'personalized_deposit_cod',
        paymentStatus: 'deposit_confirmed',
        instapayDiscountAmount: 0,
        amountDueNow: 2_750,
        amountPaid: 2_750,
        amountDueOnDelivery: 9_250,
        governorateName: 'Giza',
        createdAt: new Date('2026-07-19T11:00:00.000Z'),
      },
      {
        id: 'order-5',
        status: 'cod_pending_confirmation',
        subtotalAmount: 6_000,
        totalAmount: 7_000,
        shippingFeeAmount: 1_000,
        promoCode: null,
        promoDiscountAmount: 0,
        paymentPlan: 'cash_on_delivery',
        paymentStatus: 'cod_pending_confirmation',
        instapayDiscountAmount: 0,
        amountDueNow: 0,
        amountPaid: 0,
        amountDueOnDelivery: 7_000,
        governorateName: 'Cairo',
        createdAt: new Date('2026-07-19T12:00:00.000Z'),
      },
      {
        id: 'order-6',
        status: 'shipped',
        subtotalAmount: 8_000,
        totalAmount: 9_000,
        shippingFeeAmount: 1_000,
        promoCode: null,
        promoDiscountAmount: 0,
        paymentPlan: 'cash_on_delivery',
        paymentStatus: 'cod_due',
        instapayDiscountAmount: 0,
        amountDueNow: 0,
        amountPaid: 0,
        amountDueOnDelivery: 9_000,
        governorateName: 'Giza',
        createdAt: new Date('2026-07-19T13:00:00.000Z'),
      },
      {
        id: 'order-7',
        status: 'delivered',
        subtotalAmount: 4_000,
        totalAmount: 5_000,
        shippingFeeAmount: 1_000,
        promoCode: null,
        promoDiscountAmount: 0,
        paymentPlan: 'cash_on_delivery',
        paymentStatus: 'cash_collected',
        instapayDiscountAmount: 0,
        amountDueNow: 0,
        amountPaid: 5_000,
        amountDueOnDelivery: 0,
        governorateName: 'Giza',
        createdAt: new Date('2026-07-19T14:00:00.000Z'),
      },
    ]
    const items: ReportItemRow[] = [
      { orderId: 'order-1', productId: 'story-a', productTitle: 'Story A', quantity: 1, lineTotalAmount: 10_000 },
      { orderId: 'order-2', productId: 'story-a', productTitle: 'Story A', quantity: 2, lineTotalAmount: 7_500 },
      { orderId: 'order-3', productId: 'story-b', productTitle: 'Story B', quantity: 1, lineTotalAmount: 6_000 },
      {
        orderId: 'order-4',
        productId: 'personalized-story',
        productTitle: 'Personalized Story',
        quantity: 1,
        lineTotalAmount: 6_000,
        isPersonalized: true,
      },
      { orderId: 'order-4', productId: 'ready-book', productTitle: 'Ready Book', quantity: 1, lineTotalAmount: 6_000 },
      { orderId: 'order-5', productId: 'cod-book', productTitle: 'COD Book', quantity: 1, lineTotalAmount: 6_000 },
      { orderId: 'order-6', productId: 'shipped-book', productTitle: 'Shipped Book', quantity: 1, lineTotalAmount: 8_000 },
      { orderId: 'order-7', productId: 'story-a', productTitle: 'Story A', quantity: 1, lineTotalAmount: 4_000 },
    ]

    const report = calculateReportMetrics(orders, items, { from: '2026-07-18', to: '2026-07-19' })

    expect(report.summary).toMatchObject({
      submittedOrderCount: 7,
      acceptedOrderCount: 4,
      acceptedOrderValueAmount: 35_700,
      collectedRevenueAmount: 17_450,
      // Legacy consumers receive the same cash-collected figure, never the
      // full value of the approved 2,750-piastre deposit order.
      confirmedRevenueAmount: 17_450,
      pendingPaymentValueAmount: 8_000,
      pendingCodConfirmationValueAmount: 7_000,
      codOutstandingAmount: 18_250,
      rejectedCancelledValueAmount: 6_000,
      averageOrderValueAmount: 8_100,
      shippingFeeAmount: 6_000,
      promoDiscountAmount: 2_500,
      instapayDiscountAmount: 300,
    })
    expect(report.dailyTrend).toEqual([
      {
        date: '2026-07-18',
        orderCount: 2,
        totalAmount: 17_700,
        acceptedOrderValueAmount: 9_700,
        collectedRevenueAmount: 9_700,
        confirmedRevenueAmount: 9_700,
        pendingPaymentValueAmount: 8_000,
        pendingCodConfirmationValueAmount: 0,
        codOutstandingAmount: 0,
      },
      {
        date: '2026-07-19',
        orderCount: 5,
        totalAmount: 39_000,
        acceptedOrderValueAmount: 26_000,
        collectedRevenueAmount: 7_750,
        confirmedRevenueAmount: 7_750,
        pendingPaymentValueAmount: 0,
        pendingCodConfirmationValueAmount: 7_000,
        codOutstandingAmount: 18_250,
      },
    ])
    expect(report.topStories.find((story) => story.productId === 'personalized-story')).toEqual({
      productId: 'personalized-story',
      productTitle: 'Personalized Story',
      quantity: 1,
      orderCount: 1,
      acceptedOrderValueAmount: 6_000,
      collectedRevenueAmount: 2_750,
      confirmedRevenueAmount: 2_750,
    })
    expect(report.promoPerformance).toEqual([
      { code: 'WELCOME', redemptions: 3, discountAmount: 2_500, orderValueAmount: 29_700 },
    ])
    expect(report.governorates.find((row) => row.governorateName === 'Cairo')).toEqual({
      governorateName: 'Cairo',
      orderCount: 3,
      totalAmount: 24_700,
      shippingFeeAmount: 3_000,
    })
  })
})
